version: '3.8'

services:
  superheroes-backend:
    build: ./backend
    container_name: superheroes-backend
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/superheroes-db
    volumes:
      - ./backend:/app

  superheroes-frontend:
    build: ./frontend
    container_name: superheroes-frontend
    ports:
      - "3000:3000"
    depends_on:
      - superheroes-backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  mongo:
    image: mongo:6
    container_name: superheroes-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
