version: "3"
services:
  backend:
    build: ./backend
    container_name: 'tp2y3_backend_flask'
    command: sh -c 'python app.py'
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/backend
    depends_on:
      - redis

  redis:
    container_name: 'tp2y3_redis'
    image: redis
    ports:
      - "6379:6379"

  frontend:
    build: ./frontend
    container_name: 'tp2y3_frontend_react'
    command: sh -c 'npm install && npm run dev'
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
    stdin_open: true
    tty: true
