version: "3"
services:
  backend:
    build: ./backend
    container_name: turismo_backend
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: redis
    container_name: turismo_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  frontend:
    build: ./frontend
    container_name: turismo_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  redis_data:
